### ISSUE TITLE
Use logic from `prettier-package-json`

### ISSUE THREAD

**Issue by Airkro** [matzkoh/prettier-plugin-packagejson#7]
https://github.com/cameronhunter/prettier-package-json

It' s better and powerful than `sort-package-json`.

Can I make a PR?

**Comment by kachkaev** [comment]
| | contributors | stars on github | downloads per week |
|-|-|-|-|
| prettier-package-json | [6](https://github.com/cameronhunter/prettier-package-json/graphs/contributors) | [60](https://github.com/cameronhunter/prettier-package-json) | [7.3K](https://www.npmjs.com/package/prettier-package-json)
| sort-package-json | [25](https://github.com/keithamus/sort-package-json/graphs/contributors) | [201](https://github.com/keithamus/sort-package-json) | [141K](https://www.npmjs.com/package/sort-package-json) |

The latter is a clear winner for me.

> It' s better and powerful

Could you please elaborate?

**Comment by Airkro** [comment]
The main difference is that `sort-package-json` does not provide an option to override the default sort order. And everyone has the sort order they like.

And `prettier-package-json` also can sort `scripts` alphabetically but keeps pre and post scripts surrounding their named script.

```json
"scripts": {
  "prebuild": "prebuild",
  "build": "build",
  "postbuild": "postbuild"
}
```

Other features: https://github.com/cameronhunter/prettier-package-json#features

**Comment by kachkaev** [comment]
Customizing sort order via an option would be against Prettier’s philosophy:
https://prettier.io/docs/en/option-philosophy.html

I would not like my company to use a Prettier plugin that lets us inject opinions into it (assuming this is technically possible, about which I’m not sure). Instead of just getting our code formatted in a reasonable and consistent way, we’ll start arranging meetings to discuss which order of fields in package.json is best. In the end we will not agree and every team will use its own order. That’s expensive and counterproductive.

**Comment by Airkro** [comment]
I think you are right. There is no need to add more options.

But I do think that the default behaviour of `sort-package-json` is not reasonable. I decided to write another plugin.

Thanks.

**Comment by kachkaev** [comment]
👌 Feel free to share the result below – I'm curious to have a look!
